services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]
  _defaults:
    public: true

  pdir.mobileDe.listener.hooks:
    class: Pdir\MobileDeBundle\EventListener\HooksListener

  pdir.mobileDe.listener.dataContainer:
      class: Pdir\MobileDeBundle\EventListener\DataContainerListener
